### ISSUE TITLE
Implement python conventions

### ISSUE THREAD

**Issue by MaxBetzDLR** [DLR-SC/memilio#262]

**Comment by michaelosthege** [comment]
Hi @MaxBetzDLR,

in todays LOKI call Martin showed some of the Python code and it looks like this issue is still a ToDo..

May I recommend to set up a `pre-commit`?

Essentially you can place a `.pre-commit-config.yml` at the root level, with a config similar to this:

```yaml
exclude: ^(docs|cpp)/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
```

Plus some config in `./pyproject.toml`:

```toml
[tool.black]
line-length = 110

[tool.isort]
profile = "black"
```

You can run it in GitHub Actions:

```yaml
# .github/workflows/pre-commit.yml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
```

After committing the files, you should run the pre-commit once manually:

```bash
pre-commit run --all
```

This will make a bunch of changes, that you can then commit.
Thereafter the `pre-commit run --all` should be happy, and you can do `pre-commit install` to make it run automatically every time you make a commit. Or you can keep running it by hand.
